/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardList: typeof import('./src/components/CardList.vue')['default']
    DeliveryDetailCard: typeof import('./src/components/DeliveryDetailCard.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButton: typeof import('./src/components/SearchButton.vue')['default']
    SearchCities: typeof import('./src/components/SearchCities.vue')['default']
    SearchDropdown: typeof import('./src/components/SearchDropdown.vue')['default']
  }
}
